In [1]:
import importlib
import layers.tied
importlib.reload(layers.tied)
import tensorflow as tf
import datetime
#tf.enable_eager_execution()
print(tf.__version__)
from tensorflow.keras.callbacks import TensorBoard

1.13.1


In [ ]:
from layers.tied import TiedDenseLayer
import tensorflow as tf
from tensorflow.python.keras.models import load_model
m = load_model("/Users/talfranji/Downloads/model2way.h5")

In [ ]:
#layers.tied._test_TiedDenseLayer()
#layers.tied._test_TiedDropoutLayer()
#layers.tied._test_LocallyDenseLayer()
layers.tied._test_all()

In [15]:
def eval_tensor(t):
    return tf.Session().run(t)
def tensor2const(t):
    return tf.constant(eval_tensor(t))

Rx = tensor2const(tf.random.uniform([10,3]))
#Ry = tensor2const(tf.random.uniform([1,50]))

def move_to_center(m):
    "caclulate mean of NxM matrix - and move all m-sized vector to the middle"
    return 

print(eval_tensor(Rx))


[[0.4956671  0.91006243 0.08818448]
 [0.9417372  0.75221574 0.7670239 ]
 [0.8387631  0.8675784  0.417768  ]
 [0.70492566 0.02009404 0.00103199]
 [0.5406357  0.6690445  0.3258289 ]
 [0.11873937 0.7354553  0.02224994]
 [0.8301996  0.37822115 0.97473776]
 [0.9176452  0.7291304  0.7384045 ]
 [0.09357023 0.0989759  0.5102565 ]
 [0.29480124 0.31386065 0.01114953]]


array([[1.493914  ],
       [2.4609768 ],
       [2.1241095 ],
       [0.7260517 ],
       [1.5355091 ],
       [0.8764446 ],
       [2.1831584 ],
       [2.38518   ],
       [0.70280266],
       [0.6198114 ]], dtype=float32)

In [122]:
import util
import importlib
importlib.invalidate_caches() # allow dirsync to change files
importlib.reload(util)
util._test_cross_correlation_analysis()

TopKV2(values=array([0.00703633, 0.0028588 , 0.00136958], dtype=float32), indices=array([2, 1, 0], dtype=int32))


In [111]:
Sigma11 = tf.matmul(RxBar, tf.transpose(RxBar))
eval_tensor(tf.matmul(RxBar, tf.transpose(RxBar)))

array([[ 0.33774966, -0.0065049 ,  0.18439278,  0.00623336,  0.14094111,
         0.29368323, -0.24548613, -0.0042348 , -0.16852495,  0.12409096],
       [-0.0065049 ,  0.02222079,  0.02047715,  0.08416252,  0.00270366,
        -0.03686139,  0.02308006,  0.02239355, -0.02257827,  0.01382098],
       [ 0.18439278,  0.02047715,  0.12679887,  0.09505884,  0.08283823,
         0.12639986, -0.11406437,  0.02195192, -0.12008848,  0.08537593],
       [ 0.00623336,  0.08416252,  0.09505884,  0.321608  ,  0.02326838,
        -0.11361103,  0.06547293,  0.08503018, -0.10161489,  0.06412615],
       [ 0.14094111,  0.00270366,  0.08283823,  0.02326838,  0.06014257,
         0.11490051, -0.09793986,  0.00370404, -0.07665695,  0.05575763],
       [ 0.29368323, -0.03686139,  0.12639986, -0.11361103,  0.11490051,
         0.29943687, -0.23937584, -0.0351932 , -0.11006654,  0.08500627],
       [-0.24548613,  0.02308006, -0.11406437,  0.06547293, -0.09793986,
        -0.23937584,  0.19366929,  0.02160989

In [1]:
# RESTART - start here after kernel restart with same machine   ##############################
!rm -fR /Users/talfranji/tmp/log/fit
import sys
import importlib
#path = "/content/2WayNet-TF"
#if not path in sys.path:
#  sys.path.append(path)
import run_model
importlib.invalidate_caches() # allow dirsync to change files
importlib.reload(run_model)

<module 'run_model' from '/Users/talfranji/Dropbox/C/lior_wolf/2WayNet-TF/run_model.py'>

In [2]:
m = run_model.run_model("/Users/talfranji/Dropbox/C/lior_wolf/2WayNet-TF/MNIST.ini")


data_parameters[name] = MNIST
data_parameters[path] = /Users/talfranji/data/MNIST/
data_parameters[normalize] = 1
data_parameters[scale] = 0
data_parameters[scale_samples] = 0
data_parameters[whiten] = 0
data_parameters[pca] = 0 0
data_parameters[full] = 0
data_parameters[subsample_test] = 0
Layer X->Y build <class 'layers.tied.TiedDenseLayer'>(units=392,input_shape=(None, 392))
Layer Y->X build <class 'layers.tied.TiedDenseLayer'>(kwargs={'units': 392, 'tied_layer': <layers.tied.TiedDenseLayer object at 0xb31f93eb8>})
Noise X->Y build <class 'layers.tied.TiedDropoutLayer'>(input_shape=(None, 392))
Layer X->Y build <class 'layers.tied.TiedDenseLayer'>(units=50,input_shape=(None, 392))
Layer Y->X build <class 'layers.tied.TiedDenseLayer'>(kwargs={'units': 392, 'tied_layer': <layers.tied.TiedDenseLayer object at 0x12eade828>})
Noise X->Y build <class 'layers.tied.TiedDropoutLayer'>(input_shape=(None, 50))
Layer X->Y build <class 'layers.tied.TiedDenseLayer'>(units=392,input_shape=(None, 

1000/1000 [==============================] - 8s 8ms/step - loss: 135.6722 - tied_dense_layer_6_loss: 6.0425 - tied_dense_layer_1_loss: 6.0425 - tied_dense_layer_6_dummy_metic_for_images: 136.6000 - tied_dense_layer_6_metric_learning_rate: 1.0000e-04 - tied_dense_layer_1_dummy_metic_for_images: 136.6000 - tied_dense_layer_1_metric_learning_rate: 1.0000e-04
Epoch 42/80
1000/1000 [==============================] - 8s 8ms/step - loss: 135.5413 - tied_dense_layer_6_loss: 6.0709 - tied_dense_layer_1_loss: 6.0709 - tied_dense_layer_6_dummy_metic_for_images: 111.2640 - tied_dense_layer_6_metric_learning_rate: 1.0000e-04 - tied_dense_layer_1_dummy_metic_for_images: 111.2640 - tied_dense_layer_1_metric_learning_rate: 1.0000e-04
Epoch 43/80
1000/1000 [==============================] - 8s 8ms/step - loss: 135.3966 - tied_dense_layer_6_loss: 6.0921 - tied_dense_layer_1_loss: 6.0921 - tied_dense_layer_6_dummy_metic_for_images: 92.8720 - tied_dense_layer_6_metric_learning_rate: 1.0000e-04 - tied_dens